export {
    DEFAULT_BENEFICIARY_ID,
    DEFAULT_BENEFICIARY_NAME,
    DEFAULT_EXPENSE_CATEGORY_ID,
    DEFAULT_INCOME_CATEGORY_ID,
    SYSTEM_EXPENSE_CARD_INVOICE_CATEGORY_ID,
    INVOICE_PAYMENT_NOTE_PREFIX,
    DEFAULT_WALLET,
    DEFAULT_WALLET_ID,
} from "./financeCore";
